@php
    $projects = [
        ['number' => '01', 'title' => 'QuackAcademy Gamified Learning Tool', 'category' => 'Educational Technology (EdTech) / Gamified Learning System', 'description' => 'QuackAcademy is a gamified programming app designed for total beginners, senior high school, and first-year college students that features story-based coding adventures, multiplayer quiz races, and reward badges.', 'stack' => ['Flutter', 'Firebase'], 'image' => '/images/projects/project-1.png', 'accent' => 'coral', 'problem' => 'Beginners often find programming difficult and intimidating due to traditional learning methods that lack engagement and interactive practice.', 'solution' => 'QuackAcademy makes learning programming more engaging through story-based coding adventures, multiplayer quiz races, and reward badges.'],
        ['number' => '02', 'title' => 'Payroll System C++', 'category' => 'Desktop Application / Business Management System', 'description' => 'The Payroll Management System is a desktop application designed to help businesses manage employee information, positions, attendance, salaries, deductions, and payroll records efficiently. It automatically calculates employee earnings based on their position and pay type while securely storing all data locally for easy access and reporting.', 'stack' => ['C++', 'Qt Widgets', 'SQLite'], 'image' => '/images/projects/project-2.png', 'accent' => 'blue', 'problem' => 'Businesses need a simple and efficient way to manage employee payroll, earnings, attendance, and deductions.', 'solution' => 'A user-friendly desktop payroll management system that automates calculations and securely stores employee and payroll records locally.'],
        ['number' => '03', 'title' => 'Ridesafe', 'category' => 'Mobile Application / Safety and Security / GPS Tracking System', 'description' => 'RideSafe is an Android mobile application designed to improve personal safety by providing real-time GPS tracking and an Emergency SOS feature that allows users to quickly share their location with trusted contacts or the community during emergencies.', 'stack' => ['Flutter', 'Dart', 'C++', 'CMake', 'Swift', 'C', 'HTML'], 'image' => '/images/projects/project-3.png', 'accent' => 'lime', 'problem' => 'Individuals may face emergencies while traveling or commuting without an easy way to quickly share their location and request assistance.', 'solution' => 'RideSafe uses GPS technology and an Emergency SOS feature to help users share their real-time location and alert others when immediate assistance is needed.'],
        ['number' => '04', 'title' => 'Personal Portfolio Website', 'category' => 'Web Application / Personal Portfolio / Developer Showcase', 'description' => 'A modern and interactive personal portfolio website designed to showcase my profile, technical skills, projects, videos, and GitHub repositories. The website features dynamic transitions, responsive design, and interactive elements to create a professional and engaging user experience.', 'stack' => ['Laravel', 'PHP', 'JavaScript', 'CSS', 'Vite'], 'image' => '/images/projects/project-4.jpg', 'accent' => 'cream', 'problem' => 'Developers need a professional platform to effectively present their skills, projects, and experience to potential employers, clients, and collaborators.', 'solution' => 'The portfolio provides a visually engaging and responsive platform where users can explore my personal information, technical skills, project showcases, videos, and GitHub work through smooth animations and interactive navigation.'],
        ['number' => '05', 'title' => 'Attendance Management System', 'category' => 'Mobile Application / Attendance Management System', 'description' => 'A mobile application designed to simplify and automate student attendance tracking. The system allows attendance recording through barcode scanning and manages student and attendance records efficiently.', 'stack' => ['Flutter', 'Dart', 'PocketBase'], 'image' => '/images/projects/project-5.jpg', 'accent' => 'cream', 'problem' => 'Manual attendance tracking can be time-consuming and prone to errors, making it difficult to manage and monitor student attendance records.', 'solution' => 'The application uses barcode scanning to quickly identify students and record their attendance. Student and attendance data are stored and managed through a backend database.'],
        ['number' => '06', 'title' => 'Davao Online Market', 'category' => 'Web Application / E-Commerce / Online Marketplace', 'description' => 'Davao Online Market is a web-based marketplace designed to showcase and promote local products and sellers. The platform provides an organized way for users to browse products and explore locally available items.', 'stack' => ['Laravel', 'PHP', 'MySQL', 'JavaScript'], 'image' => '/images/projects/project-6.png', 'accent' => 'cream', 'problem' => 'Local sellers may have limited opportunities to promote their products online and reach a wider audience.', 'solution' => 'The platform provides an online marketplace where local products can be displayed and organized, making it easier for users to discover products and connect with sellers.'],
    ];
    $skills = [
        'Development' => [['name' => 'PHP', 'description' => 'Server-side logic for dependable, maintainable applications.', 'level' => 'Building with'], ['name' => 'Laravel', 'description' => 'My preferred framework for turning product ideas into structured web apps.', 'level' => 'Building with'], ['name' => 'JavaScript', 'description' => 'Bringing clarity and character to interactive interfaces.', 'level' => 'Building with'], ['name' => 'Flutter', 'description' => 'Exploring cross-platform mobile experiences with a product mindset.', 'level' => 'Exploring'], ['name' => 'HTML / CSS', 'description' => 'Semantic structure and visual systems that hold together.', 'level' => 'Building with'], ['name' => 'MySQL', 'description' => 'Organizing the data that makes applications useful.', 'level' => 'Building with']],
        'Backend / Tools' => [['name' => 'PocketBase', 'description' => 'Rapid backend prototyping for focused products and experiments.', 'level' => 'Exploring'], ['name' => 'Firebase', 'description' => 'Tools that help ideas move quickly from thought to test.', 'level' => 'Exploring'], ['name' => 'Git / GitHub', 'description' => 'Keeping experiments understandable, shareable, and moving forward.', 'level' => 'Building with'], ['name' => 'REST APIs', 'description' => 'Connecting interfaces to useful, well-shaped application data.', 'level' => 'Building with']],
        'Creative' => [['name' => 'UI Design', 'description' => 'Making digital tools feel considered, direct, and human.', 'level' => 'Building with'], ['name' => 'Photo Editing', 'description' => 'Shaping images with patience, contrast, and a clear point of view.', 'level' => 'Building with'], ['name' => 'Video Editing', 'description' => 'Editing motion and rhythm into stories people can follow.', 'level' => 'Exploring'], ['name' => 'Graphic Design', 'description' => 'Composing layouts, type, and visual language with intent.', 'level' => 'Building with']],
    ];
    $journey = [['year' => '2027', 'title' => 'Bachelor of Science in Information Technology', 'text' => 'Philippine Womens College of Davao'], ['year' => '2022', 'title' => 'Development Experience', 'text' => 'Growing through web, software, and mobile development projects that make the abstract practical.'], ['year' => '03', 'title' => 'Projects', 'text' => 'Turning classroom ideas and personal experiments into systems people can actually use.'], ['year' => '04', 'title' => 'Freelance / Creative Work', 'text' => 'Open for thoughtful collaborations across development, design, and digital storytelling.']];
    $githubUsername = 'Lizzdodizz12';
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Lee Christian D. Romero is an IT developer, web developer, and creative technologist building practical digital experiences.">
    <meta property="og:title" content="Lee Christian D. Romero | IT Developer & Web Developer"><meta property="og:description" content="Digital experiences, web applications, and creative solutions with technology and intent."><meta property="og:type" content="website">
    <title>Lee Christian D. Romero | IT Developer & Web Developer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,700;0,800;1,700;1,800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://unpkg.com/lucide-static@latest/font/Lucide.css">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body>
<div class="noise" aria-hidden="true"></div><div class="cursor-dot" aria-hidden="true"></div><div class="cursor-ring" aria-hidden="true"><span>VIEW</span></div>
<header class="site-header" data-header><a class="brand" href="#home" aria-label="Lee Christian Romero home"><span>LC</span><small>Portfolio / 2025</small></a><nav class="desktop-nav" aria-label="Primary navigation">@foreach (['About', 'Skills', 'Projects', 'Experience', 'GitHub', 'Contact'] as $item)<a href="#{{ strtolower($item) }}" data-nav-link>{{ $item }}</a>@endforeach</nav><a class="header-availability" href="#contact"><span></span> Available for work <i class="icon icon-arrow-up-right"></i></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" data-menu-toggle><i class="icon icon-menu"></i></button></header>
<div class="mobile-nav" data-mobile-nav>@foreach (['About', 'Skills', 'Projects', 'Experience', 'GitHub', 'Contact'] as $item)<a href="#{{ strtolower($item) }}">{{ $item }}<i class="icon icon-arrow-up-right"></i></a>@endforeach</div>
<main>
<section class="hero section-dark" id="home"><div class="hero-grid" aria-hidden="true"></div><div class="hero-orbit hero-orbit-one" aria-hidden="true"></div><div class="hero-orbit hero-orbit-two" aria-hidden="true"></div><div class="hero-portrait-wrap" data-parallax><div class="portrait-backdrop"></div><div class="portrait-label portrait-label-top">01 / 04<br><span>Developer<br>with a visual mind</span></div><img class="hero-portrait" src="/images/profile.png" alt="Portrait placeholder for Lee Christian D. Romero" onerror="this.style.opacity='0'"><div class="portrait-label portrait-label-bottom">Scroll to explore <i class="icon icon-arrow-down"></i></div></div><div class="hero-copy"><p class="eyebrow"><span class="eyebrow-line"></span> Independent developer / Davao City, PH</p><h1>Lee Christian<br><em>D. Romero</em></h1><p class="hero-role">IT Developer <b>&bull;</b> Web Developer <b>&bull;</b> Creative Technologist</p><p class="hero-description">I build digital experiences, web applications, and creative solutions that combine technology, design, and functionality.</p><div class="hero-actions"><a class="button button-light" href="#projects">View my work <i class="icon icon-arrow-down-right"></i></a><a class="text-link" href="#about">More about me <i class="icon icon-arrow-down"></i></a></div></div><div class="hero-side-note">Selected work<br><span>2023 — 2025</span></div></section>
<section class="about section-light" id="about"><div class="section-inner"><div class="section-kicker"><span>01</span><span>About me</span><span class="kicker-rule"></span></div><div class="about-grid"><h2 class="display-heading">I turn ideas<br>into <em>digital</em><br>experiences.</h2><div class="about-content"><p class="intro-copy">I am an IT and software developer interested in the space where useful technology meets expressive design. I enjoy building things that feel clear, practical, and a little more considered than they need to be.</p><p>My practice moves between web development, software development, UI/UX, creative technology, and the visual work around them. I am always looking for the next problem worth understanding.</p><a class="arrow-link" href="#contact">Start a conversation <i class="icon icon-arrow-up-right"></i></a></div></div><div class="stats-grid"><div class="stat"><strong>06</strong><span>Selected projects</span></div><div class="stat"><strong>12<span>+</span></strong><span>Technologies explored</span></div><div class="stat"><strong>05</strong><span>Years learning / building</span></div><div class="stat"><strong>06</strong><span>GitHub experiments</span></div></div></div></section>
<section class="skills section-cream" id="skills"><div class="section-inner"><div class="section-kicker"><span>02</span><span>Capabilities</span><span class="kicker-rule"></span></div><div class="section-heading-row"><h2 class="display-heading">Tools for making<br><em>things work.</em></h2><p class="section-note">A growing toolkit shaped by curiosity, practice, and the belief that good software should feel good to use.</p></div><div class="skills-layout"><div class="skill-tabs" role="tablist" aria-label="Skill categories">@foreach ($skills as $category => $categorySkills)<button type="button" class="skill-tab {{ $loop->first ? 'is-active' : '' }}" data-skill-tab="{{ $loop->index }}" role="tab" aria-selected="{{ $loop->first ? 'true' : 'false' }}">{{ $category }} <span>0{{ $loop->iteration }}</span></button>@endforeach</div><div class="skill-panels">@foreach ($skills as $category => $categorySkills)<div class="skill-panel {{ $loop->first ? 'is-active' : '' }}" data-skill-panel="{{ $loop->index }}" role="tabpanel">@foreach ($categorySkills as $skill)<button class="skill-item" type="button" data-skill-name="{{ $skill['name'] }}" data-skill-description="{{ $skill['description'] }}" data-skill-level="{{ $skill['level'] }}"><span>{{ $skill['name'] }}</span><i class="icon icon-arrow-up-right"></i></button>@endforeach</div>@endforeach</div><div class="skill-detail" data-skill-detail><span class="detail-label">Currently exploring</span><strong>Select a skill</strong><p>Hover or tap a tool to see how it fits into my practice.</p></div></div></div></section>
<section class="projects section-dark" id="projects"><div class="section-inner"><div class="section-kicker light"><span>03</span><span>Selected work</span><span class="kicker-rule"></span></div><div class="section-heading-row projects-heading"><h2 class="display-heading">A few things<br>I have <em>built.</em></h2><p class="section-note">A selection of practical systems and playful experiments. Every project is a chance to make the next decision with more intention.</p></div><div class="projects-list">@foreach ($projects as $project)<button class="project-item project-{{ $project['accent'] }} reveal" type="button" data-project='@json($project)' data-cursor-label="VIEW"><span class="project-meta"><b>{{ $project['number'] }}</b><span>{{ $project['category'] }}</span></span><span class="project-image"><img src="{{ $project['image'] }}" loading="lazy" alt="{{ $project['title'] }} project placeholder" onerror="this.style.opacity='0'"><span class="image-placeholder">Project<br>{{ $project['number'] }}</span></span><span class="project-info"><strong>{{ $project['title'] }}</strong><span>{{ $project['description'] }}</span><small>@foreach ($project['stack'] as $technology){{ $technology }} @endforeach</small></span><span class="project-arrow"><i class="icon icon-arrow-up-right"></i></span></button>@endforeach</div></div></section>
<section class="video-showcase section-light"><div class="section-inner"><div class="video-top"><div class="section-kicker"><span>04</span><span>In motion</span></div><p>Some ideas make more sense<br>when you see them move.</p></div><div class="video-frame reveal"><video controls preload="none" poster="/images/projects/project-3.jpg"><source src="/videos/project-demo-1.mp4" type="video/mp4">Your browser does not support the video tag.</video><div class="video-overlay"><span>Play reel</span><i class="icon icon-play"></i></div></div></div></section>
<section class="github section-cobalt" id="github"><div class="section-inner"><div class="section-kicker light"><span>05</span><span>Open source</span><span class="kicker-rule"></span></div><div class="github-intro"><h2 class="display-heading">Code, experiments<br>& <em>open source.</em></h2><a class="button button-light" href="https://github.com/lizzdodizz12" target="_blank" rel="noreferrer">Visit GitHub <i class="icon icon-arrow-up-right"></i></a></div><p class="github-note">A live repository feed can be connected here later. For now, this is a clear home for the work in progress.</p><div class="repo-grid">@foreach ([['name' => 'Lizzdodizz12', 'description' => 'A placeholder for a project you want the world to discover.', 'language' => 'JavaScript'], ['name' => 'ANOTHER_EXPERIMENT', 'description' => 'A space for documenting a question, prototype, or useful tool.', 'language' => 'PHP'], ['name' => 'OPEN_SOURCE_WORK', 'description' => 'Connect this card to the repository that best represents your practice.', 'language' => 'Flutter']] as $repo)<a class="repo-card" href="https://github.com/lizzdodizz12/quackacademy" target="_blank" rel="noreferrer"><span class="repo-top"><i class="icon icon-git-branch"></i><i class="icon icon-arrow-up-right"></i></span><strong>{{ $repo['name'] }}</strong><p>{{ $repo['description'] }}</p><span class="repo-meta"><b><i class="language-dot"></i> {{ $repo['language'] }}</b><span>Stars -- &nbsp; Forks --</span></span></a>@endforeach</div></div></section>
<section class="experience section-cream" id="experience"><div class="section-inner"><div class="section-kicker"><span>06</span><span>Journey</span><span class="kicker-rule"></span></div><div class="section-heading-row"><h2 class="display-heading">Still becoming<br><em>the developer.</em></h2><p class="section-note">The path is not a straight line. It is a collection of questions, projects, and people that keep making the work more interesting.</p></div><div class="timeline">@foreach ($journey as $item)<article class="timeline-item reveal"><div class="timeline-year">{{ $item['year'] }}</div><div class="timeline-line"><span></span></div><div class="timeline-copy"><h3>{{ $item['title'] }}</h3><p>{{ $item['text'] }}</p></div></article>@endforeach</div></div></section>
<section class="contact section-dark" id="contact"><div class="contact-glow" aria-hidden="true"></div><div class="section-inner"><div class="section-kicker light"><span>07</span><span>Get in touch</span><span class="kicker-rule"></span></div><div class="contact-grid"><div><h2 class="display-heading">Let's build<br>something <em>together.</em></h2><p class="contact-copy">Have an idea, a problem to solve, or a project that needs a thoughtful developer? I would like to hear about it.</p><div class="contact-links"><a href="mailto:romero.leechristian19@gmail.com">romero.leechristian19@gmail.com <i class="icon icon-arrow-up-right"></i></a><a href="https://github.com/lizzdodizz12" target="_blank" rel="noreferrer">GitHub / {{ $githubUsername }} <i class="icon icon-arrow-up-right"></i></a><a href="https://www.linkedin.com/in/lee-christian-romero/">LinkedIn <i class="icon icon-arrow-up-right"></i></a></div></div><form class="contact-form" data-contact-form action="{{ route('contact.send') }}" method="POST">@csrf<label>Name<input type="text" name="name" placeholder="Your name" value="{{ old('name') }}" required>@error('name')<span class="form-error">{{ $message }}</span>@enderror</label><label>Email<input type="email" name="email" placeholder="you@example.com" value="{{ old('email') }}" required>@error('email')<span class="form-error">{{ $message }}</span>@enderror</label><label>Subject<input type="text" name="subject" placeholder="What can we make?" value="{{ old('subject') }}" required>@error('subject')<span class="form-error">{{ $message }}</span>@enderror</label><label>Message<textarea name="message" rows="3" placeholder="Tell me a little about the project..." required>{{ old('message') }}</textarea>@error('message')<span class="form-error">{{ $message }}</span>@enderror</label><button class="button button-light" type="submit">Send message <i class="icon icon-arrow-up-right"></i></button><p class="form-status" role="status" aria-live="polite">@if (session('contact_success')){{ session('contact_success') }}@elseif (session('contact_error')){{ session('contact_error') }}@endif</p></form></div></div></section>
</main>
<footer class="site-footer"><div><a class="brand footer-brand" href="#home"><span>LC</span><small>Lee Christian D. Romero</small></a><p>IT Developer / Web Developer / Creative Technologist</p></div><div class="footer-right"><div class="footer-nav"><a href="#about">About</a><a href="#projects">Work</a><a href="#contact">Contact</a><a href="https://github.com/lizzdodizz12" target="_blank" rel="noreferrer">GitHub</a></div><button class="back-top" type="button" aria-label="Back to top" data-back-top><i class="icon icon-arrow-up"></i></button></div></footer>
+<div class="project-modal" data-project-modal aria-hidden="true"><div class="modal-backdrop" data-modal-close></div><div class="modal-panel" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button class="modal-close" type="button" aria-label="Close project details" data-modal-close><i class="icon icon-x"></i></button><div class="modal-image"><img data-modal-image src="" alt=""><span data-modal-number></span></div><div class="modal-content"><span class="eyebrow" data-modal-category></span><h2 id="modal-title" data-modal-title></h2><p data-modal-description></p><div class="modal-columns"><div><small>THE PROBLEM</small><p data-modal-problem></p></div><div><small>THE APPROACH</small><p data-modal-solution></p></div></div><div class="modal-stack" data-modal-stack></div><div class="modal-actions"><a class="button button-dark" href="https://github.com/lizzdodizz12" target="_blank" rel="noreferrer">GitHub <i class="icon icon-arrow-up-right"></i></a><a class="arrow-link" href="#contact" data-modal-close>Discuss a similar project <i class="icon icon-arrow-up-right"></i></a></div></div></div></div>
+</body></html>
